### ISSUE TITLE
Not working with error

### ISSUE THREAD

**Issue by izark1** [in1nit1t/pyipx#2]
Hi, I tried it to repack python elf package (built using python 3.9) after extracting it and did some modification on one file, and repacked the content as:
[root@rhel-sp-01 ~]# python3.9 pyipx.py phCodex phCodex_extracted /tmp/phph/phCodex
[*] Asset modified: libexternalcalls.so
[+] Repackaging finished

but when running the new executable I get the following error:
 Traceback (most recent call last):
  File "phCodex.py", line 24, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "algo_lib/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "algo_lib/AutoClassifier.py", line 20, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "algo_lib/ARIMA.py", line 18, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "utils/appserver_utils.py", line 11, in <module>
ImportError: /tmp/_MEIYDtDZ3/libexternalcalls.so: invalid ELF header
[4171985] Failed to execute script 'phCodex' due to unhandled exception!

**Comment by in1nit1t** [comment]
Thanks for your question. Please provide a sample so I can locate the problem.

**Comment by EMinsight** [comment]
I found the root cause, the repack will use the pyc header info for the asset which will be written to package, the header info will be wrong in some cases.
